### ISSUE TITLE
unexpected error handling 

### ISSUE THREAD

**Issue by barenko** [caolan/async#1194]
Hello! 
I'm using async to manage complex dependences on a bad production enviroment (where is connection reset, package lost, and more). I really like the async could handle errors with a try/catch block internally. The captured errors could be send to the callback if any issue happened. 

Look this example:

**What version of async are you using?**
2.0.0-rc.6

**Which environment did the issue occur in (Node version/browser version)**
node v6.2.0

**What did you do? Please include a minimal reproducable case illustrating issue.**
```js
'use strict'
const async = require('async')
async.series([
   next => {
      throw new Error('asdf')
   }
], err => console.log('Error handled', err))
```

**What did you expect to happen?**
```
Error handled Error: asdf
    at async.series.next (repl:1:27)
    at /projects/feed/node_modules/async/dist/async.js:5285:13
    at replenish (/projects/feed/node_modules/async/dist/async.js:871:21)
    at /projects/feed/node_modules/async/dist/async.js:881:15
    at eachOfLimit (/projects/feed/node_modules/async/dist/async.js:3952:26)
    at /projects/feed/node_modules/async/dist/async.js:930:20
    at _parallel (/projects/feed/node_modules/async/dist/async.js:5284:9)
    at Object.series (/projects/feed/node_modules/async/dist/async.js:5964:14)
    at repl:1:7
    at REPLServer.defaultEval (repl.js:272:27)
```

**What was the actual result?**
```
Error: asdf
    at async.series.next (repl:1:28)
    at /projects/feed/node_modules/async/dist/async.js:5285:13
    at replenish (/projects/feed/node_modules/async/dist/async.js:871:21)
    at /projects/feed/node_modules/async/dist/async.js:881:15
    at eachOfLimit (/projects/feed/node_modules/async/dist/async.js:3952:26)
    at /projects/feed/node_modules/async/dist/async.js:930:20
    at _parallel (/projects/feed/node_modules/async/dist/async.js:5284:9)
    at Object.series (/projects/feed/node_modules/async/dist/async.js:5964:14)
    at repl:1:7
    at REPLServer.defaultEval (repl.js:272:27)
```

**Comment by aearly** [comment]
Sorry, but there's no reliable way to catch thrown errors when using callbacks, or in asyncronous code.  There's no way to differentiate an error from the body of an interatee vs. an error throw in the callback.  That's only for the synchronous case too -- try/catch doesn't work if the error is thrown on a later tick in the event loop.

**Comment by wookieb** [comment]
Promises don't care about exceptions thrown in some async calls but do handle error thrown inside the function they execute. Why async can't do exactly the same?

```js
> var t = new Promise(() => { throw new Error('test'); });
undefined
> t.catch((e) => {console.log(e); });
Promise { <pending> }
> [Error: test]
```

```
> const t = new Promise(() => { setTimeout(() => {throw new Error('test');}, 100); });
undefined
> Error: test
    at Timeout._onTimeout (repl:1:55)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
> t.catch((e) => {console.log('got it'); });
Promise { <pending> }
>
```

**Comment by barocsi** [comment]
+1
