### ISSUE TITLE
TypeError: Cannot assign to read only property 'map' of object '#<Object>'

### ISSUE THREAD

**Issue by loretoparisi** [caolan/async#1275]
/examples/node_modules/async/dist/async.js:5154
    exports.map = map;
                ^

TypeError: Cannot assign to read only property 'map' of object '#<Object>'
    at /examples/node_modules/async/dist/async.js:5154:17
    at length (/examples/node_modules/async/dist/async.js:2:68)
    at Object.<anonymous> (/examples/node_modules/async/dist/async.js:5:2)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)

My modules

```
│ ├─┬ cheerio@0.20.0 
│ │ ├─┬ css-select@1.2.0 
│ │ │ ├── boolbase@1.0.0 
│ │ │ ├── css-what@2.1.0 
│ │ │ ├── domutils@1.5.1 
│ │ │ └── nth-check@1.0.1 
│ │ ├─┬ dom-serializer@0.1.0 
│ │ │ └── domelementtype@1.1.3 
│ │ ├── entities@1.1.1 
│ │ ├─┬ htmlparser2@3.8.3 
│ │ │ ├── domelementtype@1.3.0 
│ │ │ ├── domhandler@2.3.0 
│ │ │ ├── entities@1.0.0 
│ │ │ └─┬ readable-stream@1.1.14 
│ │ │   ├── core-util-is@1.0.2 
│ │ │   ├── inherits@2.0.1 
│ │ │   ├── isarray@0.0.1 
│ │ │   └── string_decoder@0.10.31 
│ │ ├─┬ jsdom@7.2.2 
│ │ │ ├── abab@1.0.3 
│ │ │ ├── acorn@2.7.0 
│ │ │ ├── acorn-globals@1.0.9 
│ │ │ ├── cssom@0.3.1 
│ │ │ ├── cssstyle@0.2.37 
│ │ │ ├─┬ escodegen@1.8.1 
│ │ │ │ ├── esprima@2.7.3 
│ │ │ │ ├── estraverse@1.9.3 
│ │ │ │ ├── esutils@2.0.2 
│ │ │ │ ├─┬ optionator@0.8.1 
│ │ │ │ │ ├── deep-is@0.1.3 
│ │ │ │ │ ├── fast-levenshtein@1.1.4 
│ │ │ │ │ ├── levn@0.3.0 
│ │ │ │ │ ├── prelude-ls@1.1.2 
│ │ │ │ │ ├── type-check@0.3.2 
│ │ │ │ │ └── wordwrap@1.0.0 
│ │ │ │ └─┬ source-map@0.2.0 
│ │ │ │   └── amdefine@1.0.0 
│ │ │ ├── nwmatcher@1.3.8 
│ │ │ ├── parse5@1.5.1 
│ │ │ ├── symbol-tree@3.1.4 
│ │ │ ├── webidl-conversions@2.0.1 
│ │ │ ├─┬ whatwg-url-compat@0.6.5 
│ │ │ │ └── tr46@0.0.3 
│ │ │ └── xml-name-validator@2.0.1 
│ │ └── lodash@4.15.0 
│ ├── diff@2.2.3 
│ ├─┬ gingerbread@0.5.0 
│ │ ├─┬ commander@2.9.0 
│ │ │ └── graceful-readlink@1.0.1 
│ │ └─┬ lodash.defaults@3.1.2 
│ │   ├─┬ lodash.assign@3.2.0 
│ │   │ ├─┬ lodash._baseassign@3.2.0 
│ │   │ │ └── lodash._basecopy@3.0.1 
│ │   │ ├─┬ lodash._createassigner@3.1.1 
│ │   │ │ ├── lodash._bindcallback@3.0.1 
│ │   │ │ └── lodash._isiterateecall@3.0.9 
│ │   │ └─┬ lodash.keys@3.1.2 
│ │   │   ├── lodash._getnative@3.9.1 
│ │   │   ├── lodash.isarguments@3.1.0 
│ │   │   └── lodash.isarray@3.0.4 
│ │   └── lodash.restparam@3.6.1 
│ ├─┬ phantom@2.1.21 
│ │ ├── linerstream@0.1.4 
│ │ ├─┬ phantomjs-prebuilt@2.1.12 
│ │ │ ├── es6-promise@3.2.1 
│ │ │ ├─┬ extract-zip@1.5.0 
│ │ │ │ ├─┬ concat-stream@1.5.0 
│ │ │ │ │ ├─┬ readable-stream@2.0.6 
│ │ │ │ │ │ └── isarray@1.0.0 
│ │ │ │ │ └── typedarray@0.0.6 
│ │ │ │ ├─┬ mkdirp@0.5.0 
│ │ │ │ │ └── minimist@0.0.8 
│ │ │ │ └─┬ yauzl@2.4.1 
│ │ │ │   └─┬ fd-slicer@1.0.1 
│ │ │ │     └── pend@1.2.0 
│ │ │ ├─┬ fs-extra@0.30.0 
│ │ │ │ ├── graceful-fs@4.1.6 
│ │ │ │ ├── jsonfile@2.3.1 
│ │ │ │ ├── klaw@1.3.0 
│ │ │ │ ├── path-is-absolute@1.0.0 
│ │ │ │ └── rimraf@2.5.4 
│ │ │ ├─┬ hasha@2.2.0 
│ │ │ │ └── is-stream@1.1.0 
│ │ │ ├── kew@0.7.0 
│ │ │ ├── progress@1.1.8 
│ │ │ ├─┬ request-progress@2.0.1 
│ │ │ │ └── throttleit@1.0.0 
│ │ │ └─┬ which@1.2.10 
│ │ │   └── isexe@1.1.2 
│ │ └─┬ winston@2.2.0 
│ │   ├── async@1.0.0 
│ │   ├── colors@1.0.3 
│ │   ├── cycle@1.0.3 
│ │   ├── eyes@0.1.8 
│ │   ├── pkginfo@0.3.1 
│ │   └── stack-trace@0.0.9 
│ ├─┬ phpjs@1.3.2 
│ │ ├─┬ cli@0.4.4-2 
│ │ │ └─┬ glob@7.0.6 
│ │ │   ├── fs.realpath@1.0.0 
│ │ │   ├─┬ inflight@1.0.5 
│ │ │   │ └── wrappy@1.0.2 
│ │ │   ├─┬ minimatch@3.0.3 
│ │ │   │ └─┬ brace-expansion@1.1.6 
│ │ │   │   ├── balanced-match@0.4.2 
│ │ │   │   └── concat-map@0.0.1 
│ │ │   └── once@1.3.3 
│ │ ├── deep-equal@0.1.2 
│ │ ├─┬ glob@3.2.1 
│ │ │ ├── graceful-fs@1.2.3 
│ │ │ ├── inherits@1.0.2 
│ │ │ └─┬ minimatch@0.2.14 
│ │ │   ├── lru-cache@2.7.3 
│ │ │   └── sigmund@1.0.1 
│ │ ├─┬ js-beautify@1.4.2 
│ │ │ ├─┬ config-chain@1.1.10 
│ │ │ │ ├── ini@1.3.4 
│ │ │ │ └── proto-list@1.2.4 
│ │ │ ├── mkdirp@0.3.5 
│ │ │ └─┬ nopt@2.1.2 
│ │ │   └── abbrev@1.0.9 
│ │ ├─┬ mocha@1.17.0 
│ │ │ ├── commander@2.0.0 
│ │ │ ├── debug@0.7.4 
│ │ │ ├── diff@1.0.7 
│ │ │ ├─┬ glob@3.2.3 
│ │ │ │ ├── graceful-fs@2.0.3 
│ │ │ │ └── minimatch@0.2.14 
│ │ │ ├── growl@1.7.0 
│ │ │ ├─┬ jade@0.26.3 
│ │ │ │ ├── commander@0.6.1 
│ │ │ │ └── mkdirp@0.3.0 
│ │ │ └── mkdirp@0.3.5 
│ │ ├─┬ send@0.1.0 
│ │ │ ├── fresh@0.1.0 
│ │ │ ├── mime@1.2.6 
│ │ │ └── range-parser@0.0.4 
│ │ └── underscore@1.5.2 
│ ├── underscore@1.8.3 
│ └─┬ watson-developer-cloud@1.12.4 
│   ├── cookie@0.2.4 
│   ├─┬ csv-stringify@1.0.4 
│   │ └── lodash.get@4.4.2 
│   ├── extend@3.0.0 
│   ├── isstream@0.1.2 
│   ├─┬ object.omit@2.0.0 
│   │ ├─┬ for-own@0.1.4 
│   │ │ └── for-in@0.1.5 
│   │ └── is-extendable@0.1.1 
│   ├─┬ object.pick@1.1.2 
│   │ └─┬ isobject@2.1.0 
│   │   └── isarray@1.0.0 
│   ├─┬ request@2.72.0 
│   │ ├── qs@6.1.0 
│   │ └── tough-cookie@2.2.2 
│   ├─┬ solr-client@0.6.0 
│   │ ├── duplexer@0.1.1 
│   │ ├─┬ httperror@0.2.3 
│   │ │ └── hnp@0.0.1 
│   │ ├─┬ json-bigint@0.1.4 
│   │ │ └── bignumber.js@1.1.1 
│   │ ├─┬ JSONStream@1.0.7 
│   │ │ ├── jsonparse@1.2.0 
│   │ │ └── through@2.3.8 
│   │ └─┬ request@2.63.0 
│   │   ├── aws-sign2@0.5.0 
│   │   ├─┬ bl@1.0.3 
│   │   │ └─┬ readable-stream@2.0.6 
│   │   │   └── isarray@1.0.0 
│   │   ├─┬ har-validator@1.8.0 
│   │   │ └── bluebird@2.11.0 
│   │   ├─┬ http-signature@0.11.0 
│   │   │ ├── asn1@0.1.11 
│   │   │ ├── assert-plus@0.1.5 
│   │   │ └── ctype@0.5.3 
│   │   └── qs@5.1.0 
│   ├── string@3.3.1 
│   ├── vcap_services@0.1.7 
│   └─┬ websocket@1.0.23 
│     ├─┬ debug@2.2.0 
│     │ └── ms@0.7.1 
│     ├── nan@2.4.0 
│     ├── typedarray-to-buffer@3.1.2 
│     └── yaeti@0.0.4 
├─┬ @priv/mymodule1
│ ├─┬ @priv/submymodule2
│ │ ├── cookie-cutter@0.1.1  (git://github.com/zimok/cookie-cutter.git#fc8f6d93c30c8e8370f0c9c50cdee8d97306fb61)
│ │ ├── mixto@1.0.0 
│ │ ├── simply-deferred@2.4.0 
│ │ └─┬ superagent@0.16.0 
│ │   ├── cookiejar@1.3.0 
│ │   ├── emitter-component@1.0.0 
│ │   ├── formidable@1.0.14 
│ │   ├── methods@0.0.1 
│ │   ├── mime@1.2.5 
│ │   ├── qs@0.6.5 
│ │   └── reduce-component@1.0.1 
│ ├── async@0.1.15 
│ ├─┬ cheerio@0.10.8 
│ │ ├─┬ cheerio-select@0.0.3 
│ │ │ └─┬ CSSselect@0.7.0 
│ │ │   ├── CSSwhat@0.4.7 
│ │ │   └── domutils@1.4.3 
│ │ ├── entities@0.5.0 
│ │ ├─┬ htmlparser2@2.6.0 
│ │ │ ├── domhandler@2.0.3 
│ │ │ └── domutils@1.0.1 
│ │ └── underscore@1.4.4 
│ ├─┬ redis@2.6.2 
│ │ ├── double-ended-queue@2.1.0-0 
│ │ ├── redis-commands@1.2.0 
│ │ └── redis-parser@2.0.4 
│ └─┬ request@2.74.0 
│   ├── aws-sign2@0.6.0 
│   ├── aws4@1.4.1 
│   ├─┬ bl@1.1.2 
│   │ └─┬ readable-stream@2.0.6 
│   │   ├── isarray@1.0.0 
│   │   ├── process-nextick-args@1.0.7 
│   │   └── util-deprecate@1.0.2 
│   ├── caseless@0.11.0 
│   ├─┬ combined-stream@1.0.5 
│   │ └── delayed-stream@1.0.0 
│   ├── forever-agent@0.6.1 
│   ├─┬ form-data@1.0.1 
│   │ └── async@2.0.1 
│   ├─┬ har-validator@2.0.6 
│   │ ├─┬ chalk@1.1.3 
│   │ │ ├── ansi-styles@2.2.1 
│   │ │ ├── escape-string-regexp@1.0.5 
│   │ │ ├─┬ has-ansi@2.0.0 
│   │ │ │ └── ansi-regex@2.0.0 
│   │ │ ├── strip-ansi@3.0.1 
│   │ │ └── supports-color@2.0.0 
│   │ ├─┬ is-my-json-valid@2.13.1 
│   │ │ ├── generate-function@2.0.0 
│   │ │ ├─┬ generate-object-property@1.2.0 
│   │ │ │ └── is-property@1.0.2 
│   │ │ ├── jsonpointer@2.0.0 
│   │ │ └── xtend@4.0.1 
│   │ └─┬ pinkie-promise@2.0.1 
│   │   └── pinkie@2.0.4 
│   ├─┬ hawk@3.1.3 
│   │ ├── boom@2.10.1 
│   │ ├── cryptiles@2.0.5 
│   │ ├── hoek@2.16.3 
│   │ └── sntp@1.0.9 
│   ├─┬ http-signature@1.1.1 
│   │ ├── assert-plus@0.2.0 
│   │ ├─┬ jsprim@1.3.0 
│   │ │ ├── extsprintf@1.0.2 
│   │ │ ├── json-schema@0.2.2 
│   │ │ └── verror@1.3.6 
│   │ └─┬ sshpk@1.10.0 
│   │   ├── asn1@0.2.3 
│   │   ├── assert-plus@1.0.0 
│   │   ├─┬ bcrypt-pbkdf@1.0.0 
│   │   │ └── tweetnacl@0.14.3 
│   │   ├─┬ dashdash@1.14.0 
│   │   │ └── assert-plus@1.0.0 
│   │   ├── ecc-jsbn@0.1.1 
│   │   ├─┬ getpass@0.1.6 
│   │   │ └── assert-plus@1.0.0 
│   │   ├── jodid25519@1.0.2 
│   │   ├── jsbn@0.1.0 
│   │   └── tweetnacl@0.13.3 
│   ├── is-typedarray@1.0.0 
│   ├── json-stringify-safe@5.0.1 
│   ├─┬ mime-types@2.1.11 
│   │ └── mime-db@1.23.0 
│   ├── node-uuid@1.4.7 
│   ├── oauth-sign@0.8.2 
│   ├── qs@6.2.1 
│   ├── stringstream@0.0.5 
│   ├── tough-cookie@2.3.1 
│   └── tunnel-agent@0.4.3 
└─┬ aws-sdk@2.5.5 
  ├── jmespath@0.15.0 
  ├── sax@1.1.5 
  ├─┬ xml2js@0.4.15 
  │ └── sax@1.2.1 
  └─┬ xmlbuilder@2.6.2 
    └── lodash@3.5.0 
```

**Comment by loretoparisi** [comment]
My guess is that this issue could be related to this code

```javascript
Object.defineProperty(Object.prototype, 'map', {
      value: function(f, ctx) {
          ctx = ctx || this;
          var self = this, result = {};
          Object.keys(self).forEach(function(k) {
              result[k] = f.call(ctx, self[k], k, self);
          });
          return result;
      }
```

that extends a prototype of the array `map` to objects.
In fact in this case, depending on inclusion of files, the 

```javascript
exports.map = map;
```

will raise  `TypeError: Cannot assign to read only property 'map' of object '#'`

**Comment by megawac** [comment]
Where is the `Object.defineProperty(Object.prototype, 'map', {` coming from? also it's widely considered extremely harmful to extend the `Object.prototype`. I would suggest instead of extending the object prototype to instead define `Object.map` or similar

**Comment by loretoparisi** [comment]
@megawac yes I have removed that `map` and renamed `mapObject` or something like that.
