### ISSUE TITLE
reflectAll with async.auto task objects

### ISSUE THREAD

**Issue by MaerF0x0** [caolan/async#1295]
**What version of async are you using?**
2.0.1
**Which environment did the issue occur in (Node version/browser version)**
node
**What did you do? Please include a minimal reproducable case illustrating issue.**

``` javascript
async = require("async");

async.auto(async.reflectAll({
    one: function(cb_a) {
        setTimeout(function(){cb_a(null, "A")}, 1000);
    },
    // I believe the issue is "two" task is an array because of dependency on "one"
    two: ["one", function(results, cb_a) {
        setTimeout(function() {cb_a(new Error("Two error"))}, 1000);
    }],
}, function(err, results)  {
    console.log("in final", err, results);
}));
```

**What did you expect to happen?**
It would properly reflect all the tasks, skipping the dependency strings until it found the final function
**What was the actual result?**

```
            return fn.apply(this, args);
                      ^

TypeError: fn.apply is not a function
    at reflectOn (/Users/user/code/pushapi/node_modules/async/dist/async.js:4090:23)
    at /Users/user/code/pushapi/node_modules/async/dist/async.js:355:16
    at /Users/user/code/pushapi/node_modules/async/dist/async.js:338:31
    at runTask (/Users/user/code/pushapi/node_modules/async/dist/async.js:1662:17)
    at /Users/user/code/pushapi/node_modules/async/dist/async.js:1602:17
    at processQueue (/Users/user/code/pushapi/node_modules/async/dist/async.js:1612:17)
    at Object.auto (/Users/user/code/pushapi/node_modules/async/dist/async.js:1598:9)
    at Object.<anonymous> (/Users/user/code/pushapi/tryreflect.js:3:7)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
```

i think it can be fixed by  changing https://github.com/caolan/async/blob/master/lib/reflectAll.js#L79  to check if the task is an array and take the last item, something like:

**reflectAll.js**

``` javascript
export default function reflectAll(tasks) {
    var results;
    if (isArray(tasks)) {
        results = _arrayMap(tasks, reflect);
    } else {
        results = {};
        forOwn(tasks, function(task, key) {
             if(isArray(task) {
                 results[key] = reflect.call(this, task[task.length -1]);
             } else { 
                 results[key] = reflect.call(this, task);
             }
        });
    }
    return results;
}
```

**Comment by megawac** [comment]
Yeah, I'm not sure how I'd like to handle this from an api perspective. Maybe @aearly has thoughts but I don't know I'd like reflectAll specifically tuned for auto use.

For now I'd write it like this

```js

async.auto({
    one: async.reflect(function(cb_a) {
        setTimeout(function(){cb_a(null, "A")}, 1000);
    }),
    // I believe the issue is "two" task is an array because of dependency on "one"
    two: ["one", async.reflect(function(results, cb_a) {
        setTimeout(function() {cb_a(new Error("Two error"))}, 1000);
    })],
}, function(err, results)  {
    console.log("in final", err, results);
});
```

**Comment by megawac** [comment]
I think I'd be against changing the reflectAll behaviour for this case

**Comment by aearly** [comment]
I don't think it's too bad to try to be compatible with our own flavors of objects.  For example -- the only reason we added support for objects was to support the object flavor of `parallel` and the like.

We could also consider adding a separate `reflectAllAuto` function just for this case.  Otherwise, we iterate the object, and if the prop is an array, we just wrap the last value in the array.

**Comment by megawac** [comment]
I'm going to close this and see if it comes up again
