### ISSUE TITLE
Error: Callback was already called.

### ISSUE THREAD

**Issue by sumitridhal** [caolan/async#1343]
async version: 2.1.4

I'm trying to import data from one database to another database.
1. Getting data from DB2 using jt400
2. Inserting data into mysql (not mentioned in code for now)

The query to select data is mentioned in `var reports` which has the data:
```js
[{
  "id": 101,
  "query": "SELECT * FROM BI001CV1  ",
  "columns": ["ACCTYPE","COUNT","TOTAL","DATE"],
  "table": "ORDER101"
},
{
  "id": 102,
  "query": "SELECT *  FROM BI001CV1 ",
  "columns": ["ACCTYPE","COUNT","TOTAL","DATE"],
  "table": "ORDER101"
}]
```

The code is working fine till first iteration. But on second iteration getting `Error: Callback was already called.`
My code is:

 ```js
var myData;

function ReportJS(data) {
    this.id = data.id;
    this.name = data.name;
    this.type = data.type;
    this.description = data.description;
    this.query = data.query.replace('TDATE', date);
    this.columns = data.columns;
    this.table = data.table;
}

var getData = function(row, callback) {
    myData = new ReportJS(row);
    console.log('Fetching Data For Report ID: ' + myData.id);

    var select = function(fn) {
        console.log('calling select ... ' + myData.id);

        database.execute(myData.query);
        database.on('execute', function(error, data) {
            console.log('DB2 exe... ' + myData.id);
	    var feilds = myData.columns;
	    var cols = [];
            if (error) return callback(error, null);
            async.each(data, function(key, value) {
                var subcols = [];
                feilds.forEach(function(index, pair) {
                    subcols.push(key[feilds[pair]]);
                });
                cols.push(subcols);
            });
            console.log('select ended... ' + myData.id);
            return fn(cols);
        });
    };

    var insert = function(data, cb) {
        console.log('calling insert ... ' + myData.id);       

        setTimeout(function() { 
		return cb(null, data.length + ' success'); 
        }, 1000);

    };

    select(function(result) {
        insert(result, function(err, data) {
            console.log(data);   
            return callback();  //Line No. 71
        });
    });
}
async.eachSeries(reports, getData, function(err) {
    if (err) console.log(err);
    connection.end();
});
```
Output:

```
Fetching Data For Report ID: 101
calling select ... 101
DB2 exe... 101
select ended... 101
calling insert ... 101
17 success
Fetching Data For Report ID: 102
calling select ... 102
DB2 exe... 102
select ended... 102
calling insert ... 102
DB2 exe... 102
select ended... 102
calling insert ... 102
17 success
/home/sridhal/node/node_modules/async/dist/async.js:837
        if (fn === null) throw new Error("Callback was already called.");
                               ^
Error: Callback was already called.
    at /home/sridhal/node/node_modules/async/dist/async.js:837:32
    at /home/sridhal/node/jt400/db2mySQL.js:71:20
    at null._onTimeout (/home/sridhal/node/jt400/db2mySQL.js:63:10)
    at Timer.listOnTimeout (timers.js:110:15)
```

**Comment by aearly** [comment]
You aren't removing the event listener for `database.on('execute', ...`
