### ISSUE TITLE
[question] - try to use `async/timeout` write a the http request retry

### ISSUE THREAD

**Issue by mrdulin** [caolan/async#1344]
```js
const timeout =  require('async/timeout');
const superagent = require('superagent');
const fs = require('fs');
const path = require('path');

//需求：异步操作的时间小于1秒时，正常执行，如果异步操作的时间大于1秒，抛出err对象，'ETIMEDOUT'

const searchBook = (query, cb) => {
	const url = `http://it-ebooks-api.info/v1/search/${query}`;

	superagent.get(url).then(res => {
		cb(null, {query, body: res.body});
	}).catch(err => {
		cb(err);
	});
}

const searchBookWrapped = timeout(searchBook, 1500);
const query = 'angular';
const retryDelay = 2000, maxRetryCount = 5;
searchBookWrapped.retryCount = 1;

const searchHandle = (err, data) => {
	if(err) {
		if(err.code === 'ETIMEDOUT') {
			const {retryCount} = searchBookWrapped;
			if(retryCount < maxRetryCount) {
				console.log(`请求超时，正在重新尝试请求. ${retryCount}次`)
				searchBookWrapped.retryCount++;
				searchBookWrapped.call(null, query, searchHandle);
			} else {
				return console.error(err.stack);
			}
		} else {
			return console.error(err.stack);
		}
	} else {
		const result = {data};
		fs.writeFileSync(path.resolve(__dirname, 'data.json'), JSON.stringify(result, null, 4));
		console.log('请求成功，数据写入完毕!');
	}
}

searchBookWrapped(query, searchHandle);
```

The problem is, if first task `timeout`,  my rest task will also `timeout`.

Here is my debug info: 
```bash
node --debug-brk=17739 --nolazy async/utils/timeout/index.js 
Debugger listening on 127.0.0.1:17739
请求超时，正在重新尝试请求. 1次
请求超时，正在重新尝试请求. 2次
请求超时，正在重新尝试请求. 3次
请求超时，正在重新尝试请求. 4次
Error: Callback function "searchBook" timed out.
    at Timeout.timeoutCallback [as _onTimeout] (/Users/elsa/Desktop/workspace/dul-workspace/Training.nodejs/node_modules/async/timeout.js:69:21)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

I can not figure out. help me please. Thanks.

**Comment by hargasinski** [comment]
Hi @mrdulin, sorry about the late reply.

You could do something along the lines of 
```js
// ...
const searchBookWrapped = timeout(searchBook, 1500);
const query = 'angular';
const retryDelay = 2000, maxRetryCount = 5;
searchBookWrapped.retryCount = 1;

const searchHandle = (err, data) => {
	if(err) {
		if(err.code === 'ETIMEDOUT') {
			const {retryCount} = searchBookWrapped;
			if(retryCount < maxRetryCount) {
				console.log(`请求超时，正在重新尝试请求. ${retryCount}�次`)
                                const innerSearchBook = timeout(searchBook, retryDelay); // <-- this line changed
				searchBookWrapped.retryCount++;
				innerSearchBook.call(null, query, searchHandle); // <-- call innerSearchBook
			} else {
				return console.error(err.stack);
			}
		} else {
			return console.error(err.stack);
		}
	} else {
		const result = {data};
		fs.writeFileSync(path.resolve(__dirname, 'data.json'), JSON.stringify(result, null, 4));
		console.log('请求成功，数据写入完毕!');
	}
}

searchBookWrapped(query, searchHandle);
```
Although, in that case, you should change `retryCount` to simply be a variable, as opposed to a property of `searchBookWrapped`.

An even nicer way of achieving the same result would be to use [async.retry](http://caolan.github.io/async/docs.html#retry). The code would look something like:
```js
const retry =  require('async/retry');
// ...
const query = 'angular';
const retryDelay = 2000, maxRetryCount = 5;
let retryCount = 0;

retry({times: maxRetryCount, errorFilter: err => err.code === 'ETIMEDOUT'}, function(callback, results) {
    retryCount++;
    const searchBookWrapped = timeout(searchBook, retryCount === 1 ? 1500 : retryDelay);
    searchBookWrapped(query, callback);
}, function(err, data) {
    if (err) return console.error(err.stack);

    const result = {data};
    fs.writeFileSync(path.resolve(__dirname, 'data.json'), JSON.stringify(result, null, 4));
    console.log('请求成功，数据写入完毕!');
});
```

**Comment by mrdulin** [comment]
@hargasinski Thanks very much.
