### ISSUE TITLE
2.x causing problems with Bluebird promises

### ISSUE THREAD

**Issue by xmaestro** [caolan/async#1356]
Hi. First of all, thanks for this cool library.

I have been using 1.5.x for some time now and had no problems. But when i switched to 2.1.4, i started getting warnings from Bluebird library saying i was not returning from within Promises.

Here is a sample stack trace:

```
Warning: a promise was created in a handler but was not returned from it
    at Deferred.toPromise (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/waterline/lib/waterline/query/deferred.js:494:61)
    at Deferred.then (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/waterline/lib/waterline/query/deferred.js:505:15)
    at async.waterfall.File.find.file_course_id (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/api/controllers/AcademyMemberController.js:1705:28)
    at fn (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/sails/node_modules/async/lib/async.js:741:34)
    at /home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/sails/node_modules/async/lib/async.js:1208:16
    at /home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/sails/node_modules/async/lib/async.js:166:37
    at /home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/sails/node_modules/async/lib/async.js:701:43
    at /home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/sails/node_modules/async/lib/async.js:167:37
    at /home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/sails/node_modules/async/lib/async.js:1204:30
    at /home/rizwanhussain/www/nicheacademy_spa/v2-dev/api/controllers/AcademyMemberController.js:1695:40
    at wrapper (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/waterline/node_modules/lodash/index.js:3592:19)
    at applyInOriginalCtx (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/waterline/lib/waterline/utils/normalize.js:324:18)
    at callback.success (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/waterline/node_modules/switchback/lib/factory.js:58:28)
    at returnResults (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/waterline/lib/waterline/query/finders/basic.js:390:9)
    at /home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/waterline/lib/waterline/query/finders/basic.js:271:16
    at /home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/waterline/lib/waterline/query/finders/operations.js:83:7
    at /home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/waterline/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/waterline/node_modules/async/lib/async.js:236:30)
    at Object.async.forEach.async.each (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/waterline/node_modules/async/lib/async.js:209:22)
    at /home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/waterline/lib/waterline/query/finders/operations.js:436:11
    at /home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/waterline/lib/waterline/query/finders/operations.js:574:5
    at /home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/waterline/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/waterline/node_modules/async/lib/async.js:236:30)
    at Object.async.forEach.async.each (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/waterline/node_modules/async/lib/async.js:209:22)
    at _buildChildOpts (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/waterline/lib/waterline/query/finders/operations.js:464:9)
    at _execChildOpts (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/waterline/lib/waterline/query/finders/operations.js:432:8)
    at /home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/waterline/lib/waterline/query/finders/operations.js:81:10
    at wrapper (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/waterline/node_modules/lodash/index.js:3592:19)
    at applyInOriginalCtx (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/waterline/lib/waterline/utils/normalize.js:324:18)
    at callback.success (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/waterline/node_modules/switchback/lib/factory.js:58:28)
    at /home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/sails-mysql/lib/connections/spawn.js:120:16
    at Object.module.exports.poolfully [as releaseConnection] (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/sails-mysql/lib/connections/release.js:28:12)
    at /home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/sails-mysql/lib/connections/spawn.js:105:35
    at Query._callback (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/sails-mysql/lib/adapter.js:840:11)
    at Query.Sequence.end (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
    at Query.EofPacket (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:128:8)
    at Protocol._parsePacket (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:534:20)
From previous event:
    at Deferred.then (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/waterline/lib/waterline/query/deferred.js:505:27)
    at async.waterfall.Course.findOne.course_id (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/api/controllers/AcademyMemberController.js:1690:28)
    at fn (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/sails/node_modules/async/lib/async.js:741:34)
    at /home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/sails/node_modules/async/lib/async.js:1208:16
    at /home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/sails/node_modules/async/lib/async.js:166:37
    at /home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/sails/node_modules/async/lib/async.js:701:43
    at /home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/sails/node_modules/async/lib/async.js:167:37
    at /home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/sails/node_modules/async/lib/async.js:1204:30
    at /home/rizwanhussain/www/nicheacademy_spa/v2-dev/api/controllers/AcademyMemberController.js:1679:40
    at tryCatcher (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/sails-mock-models/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/sails-mock-models/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/sails-mock-models/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromiseAtPostResolution (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/sails-mock-models/node_modules/bluebird/js/main/promise.js:244:10)
    at Async._drainQueue (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/sails-mock-models/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/sails-mock-models/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/rizwanhussain/www/nicheacademy_spa/v2-dev/node_modules/sails-mock-models/node_modules/bluebird/js/main/async.js:15:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

I'm not sure what would cause that because i added return to every statement in my code and when i switch back to 1.5, it starts working fine without warnings. 

Also, here is a bit of code that causes the above warning:

```
AcademyCourse.findOne({
            course_id: course_id,
            academy_id: academy_id,
            is_course_owner: '1'
        }).then(function (ac) {
            if (ac) {
                return async.waterfall([
                    function (callback) {
                        CourseSubscriber.find({
                            course_id: ac.course_id
                        }).then(function (subscribers) {
                            if (subscribers) {
                                if (subscribers.length > 0) {
                                    return callback(new Error('You cannot delete a course which has students enrolled!'))
                                }
                                return callback(null, true);
                            }
                            return callback(null, true);
                        }).catch(function (error) {
                            return callback(error);
                        });
                    },
                    function (done, callback) {
                        AcademyCourse.find({
                            course_id: ac.course_id,
                            is_course_owner: '0'
                        }).then(function (acRows) {
                            if (acRows) {
                                if (acRows.length > 0) {
                                    return callback(new Error('You cannot delete this course as it has been shared across other academies!'))
                                }
                                return callback(null, true);
                            }
                            return callback(null, true);
                        }).catch(function (error) {
                            return callback(error);
                        });
                    },
                    function (done, callback) {
                        Course.findOne({
                            course_id: course_id
                        }).then(function (course) {
                            if (course) {
                                if (course.course_image != "not_given" && course.course_image != null) {
                                    AwsService.deleteObject(course.course_image).then(function (deleted) {
                                        return callback(null, true)
                                    }).catch(function (error) {
                                        return callback(null, true)
                                    })
                                } else {
                                    return callback(null, true)
                                }
                            } else {
                                return callback(new Error('No course found!'));
                            }
                        }).catch(function (error) {
                            return callback(error);
                        });
                    },
                    function (done, callback) {
                        File.find({
                            file_course_id: course_id,
                            file_ac_url: academy_url
                        }).then(function (files) {
                            return async.each(files, function (file, cb) {
                                AwsService.deleteObject(file.file_hash_name).then(function (deleted) {
                                    return cb();
                                }).catch(function (error) {
                                    return cb();
                                })
                            }, function (error) {
                                return callback(null, true)
                            })
                        }).catch(function (error) {
                            return callback(null, true)
                        })
                    },
                    function (done, callback) {
                        LabSubmission.find({
                            academy_id: academy_id,
                            course_id: course_id
                        }).then(function (files) {
                            return async.each(files, function (file, cb) {
                                if (file.file_hash_name != null && file.file_hash_name != '') {
                                    AwsService.deleteObject(file.file_hash_name).then(function (deleted) {
                                        return cb();
                                    }).catch(function (error) {
                                        return cb();
                                    })
                                }
                                return cb();
                            }, function (error) {
                                return callback(null, true)
                            })
                        }).catch(function (error) {
                            return callback(null, true)
                        })
                    },
                    function (done, callback) {
                        AcademyCourse.destroy({
                            course_id: ac.course_id,
                            academy_id: academy_id
                        }).then(function (deleted) {
                            return callback(null, true);
                        }).catch(function (error) {
                            return callback(error);
                        });
                    },
                    function (done, callback) {
                        Course.destroy({
                            course_id: ac.course_id
                        }).then(function (deleted) {
                            return callback(null, true);
                        }).catch(function (error) {
                            return callback(error);
                        });
                    }
                ], function (error, done) {
                    if (error) {
                        return res.json({
                            result: false,
                            message: error.message
                        });
                    }
                    return res.json({
                        result: true,
                        message: req.__('admin_edit_ac_success')
                    });
                });
            } else {
                return res.json({
                    result: false,
                    message: "Course not found!"
                });
            }
        }).catch(function (error) {
            return res.json({
                result: false,
                message: error.message
            });
        });
```

Am i missing something or is it a bug?

Thanks.

**Comment by xmaestro** [comment]
Never mind that. I fixed it by updating Waterline ORM which seemed to be the not returning some values.
