### ISSUE TITLE
TypeError: Cannot read property 'Symbol(Symbol.toStringTag)' of undefined

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1438]
I can't tell if this error is coming from this library or the mongoose library (v. 2.4.1)

```
  => CDT server has caught an "uncaughtException" =>  TypeError: Cannot read property 'Symbol(Symbol.toStringTag)' of undefined
    at isAsync (/Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/async/dist/async.js:175:32)
    at wrapAsync (/Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/async/dist/async.js:179:12)
    at /Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/async/dist/async.js:3830:9
    at replenish (/Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/async/dist/async.js:946:17)
    at iterateeCallback (/Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/async/dist/async.js:931:17)
    at /Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/async/dist/async.js:906:16
    at /Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/async/dist/async.js:3835:13
    at /Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/async/dist/async.js:3838:9
    at /Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/async/dist/async.js:421:16
    at replenish (/Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/async/dist/async.js:941:25)
    at iterateeCallback (/Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/async/dist/async.js:931:17)
    at /Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/async/dist/async.js:906:16
    at /Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/async/dist/async.js:3835:13
    at /Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/async/dist/async.js:998:13)
    at /Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/async/dist/async.js:906:16
    at /Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/mongoose/lib/model.js:3435:16
    at /Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/mongoose/lib/model.js:938:19
    at done (/Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/mongoose/lib/model.js:960:17)
    at create (/Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/mongoose/lib/model.js:972:24)
    at /Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/mongoose/lib/model.js:985:7
    at /Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/mongoose/lib/utils.js:512:16
    at handleCallback (/Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/mongoose/node_modules/mongodb/lib/utils.js:95:56)
    at /Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/mongoose/node_modules/mongodb/lib/db.js:1150:49
    at handleCallback (/Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/mongoose/node_modules/mongodb/lib/utils.js:95:56)
    at /Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/mongoose/node_modules/mongodb/lib/db.js:1674:5
    at handleCallback (/Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/mongoose/node_modules/mongodb/lib/utils.js:95:56)
    at /Users/alexamil/WebstormProjects/nabisco/cdt-now/node_modules/mongoose/node_modules/mongodb/lib/cursor.js:852:16
```

any idea what this be resulting from? weird

**Comment by ORESoftware** [comment]
nevermind! totally my fault, this was because of non-existent import in my codebase

const {x} = require('Z');

where x wasn't event close to existing lol
