### ISSUE TITLE
Listen for first drain event on queue

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1441]
I have this:

```js
 const q = async.queue(function (task: Function, cb: Function) {
      task(cb);
    }, 2);

 q.once('drain', cb);
```

I got this error:

```console
        q.once('drain', cb);
          ^

TypeError: q.once is not a function
    at findItems (/Users/alexamil/WebstormProjects/oresoftware/npm-link-up/index.js:168:11)
    at newTask (/Users/alexamil/WebstormProjects/oresoftware/npm-link-up/node_modules/async/dist/async.js:2119:33)
    at runTask (/Users/alexamil/WebstormProjects/oresoftware/npm-link-up/node_modules/async/dist/async.js:1647:13)
    at /Users/alexamil/WebstormProjects/oresoftware/npm-link-up/node_modules/async/dist/async.js:1589:13
```

I would except it to be a standard Node.js / JS event emitter. But I guess that wouldn't make that much sense, necessarily.

Is there a way to listen just for the first drain event?

**Comment by ORESoftware** [comment]
lol whoops, I read the docs again

it's 

`q.drain = fn;`

not 

`q.on('drain', fn);`

my bad
