### ISSUE TITLE
Node Js socket.io not found

### ISSUE THREAD

**Issue by sanjayrajpurohit36** [caolan/async#1479]
**What version of async are you using?**

**Which environment did the issue occur in (Node version/browser version)**
node version

**What did you do? Please include a minimal reproducable case illustrating issue.**

**What did you expect to happen?**
run of server

**What was the actual result?**
Error: Cannot find module 'socket.io'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\xampp\htdocs\quechno\index.js:3:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

**Comment by aearly** [comment]
Sounds like you need to `npm install socket.io`
