### ISSUE TITLE
typescript problem? fn[Symbol.toStringTag] === 'AsyncFunction'

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1523]
I have tried async versions 2.4.1, 2.5.0 and 2.6.0...

I install async with `npm install -D async` not `npm install -S async`, btw.

I have this .ts file:

```typescript
import http = require('http');
import async = require('async');
import request = require('request');
import {HavenData} from "./simple-server";
import assert = require('assert');
import util = require('util');

const tasks = new Array(5000).map(function () {
  return function (cb: Function) {
    
    const r = Math.random();
    let m : string;
    
    const opts = {
      hostname: 'localhost',
      path: '/',
      port: 6969,
      qs: {timeout: Math.ceil(30*Math.random())} as Partial<HavenData>
    };
    
    if (r < 0.33) {
      opts.qs.timeoutThrow = true;
      m = 'timeout throw B';
    }
    else if (r < 0.66) {
      opts.qs.throwSync = true;
      m = 'sync throw A';
    }
    else{
      opts.qs.promiseThrow = true;
      m = 'promise throw C';
    }
  
    const to = setTimeout(function(){
      cb(new Error('request with the following options timedout: ' + util.inspect(opts)));
    }, 800);
    
    http.get(opts, function (resp) {
      
      let data = '';
      
      resp.on('data', function (d) {
        data += String(d);
      });
      
      resp.once('end', function () {
        
        try{
          const v = JSON.parse(data);
          assert(String(v.error).match(m))
        }
        catch(err){
          return cb(err);
        }
        
        cb(null);
        
      });
      
    });
    
  }
});


async.parallelLimit(tasks, 15, function(err){
    if(err) throw err;
    console.log('passed.');
});
```

which gets transpiled to:

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var http = require("http");
var async = require("async");
var assert = require("assert");
var util = require("util");
var tasks = new Array(5000).map(function () {
    return function (cb) {
        var r = Math.random();
        var m;
        var opts = {
            hostname: 'localhost',
            path: '/',
            port: 6969,
            qs: { timeout: Math.ceil(30 * Math.random()) }
        };
        if (r < 0.33) {
            opts.qs.timeoutThrow = true;
            m = 'timeout throw B';
        }
        else if (r < 0.66) {
            opts.qs.throwSync = true;
            m = 'sync throw A';
        }
        else {
            opts.qs.promiseThrow = true;
            m = 'promise throw C';
        }
        var to = setTimeout(function () {
            cb(new Error('request with the following options timedout: ' + util.inspect(opts)));
        }, 800);
        http.get(opts, function (resp) {
            var data = '';
            resp.on('data', function (d) {
                data += String(d);
            });
            resp.once('end', function () {
                try {
                    var v = JSON.parse(data);
                    assert(String(v.error).match(m));
                }
                catch (err) {
                    return cb(err);
                }
                cb(null);
            });
        });
    };
});
async.parallelLimit(tasks, 15, function (err) {
    if (err)
        throw err;
    console.log('passed.');
});

```

when I run it I get this error:

```
/Users/alexamil/WebstormProjects/oresoftware/domain-haven/node_modules/async/dist/async.js:175
    return supportsSymbol && fn[Symbol.toStringTag] === 'AsyncFunction';
                               ^

TypeError: Cannot read property 'Symbol(Symbol.toStringTag)' of undefined
    at isAsync (/Users/alexamil/WebstormProjects/oresoftware/domain-haven/node_modules/async/dist/async.js:175:32)
    at wrapAsync (/Users/alexamil/WebstormProjects/oresoftware/domain-haven/node_modules/async/dist/async.js:179:12)

```

**Comment by hargasinski** [comment]
Thanks for the question!

This is a quirk of how the `Array` constructor works, you're actually passing an array of empty slots to `parallelLimit` as opposed to the expected array of functions. Changing to
```js
 const tasks = new Array(5000).map(function () {
```
to
```js
 const tasks = new Array(5000).fill(function () {
```
should fix the issue. Basically, the callback you pass to the `map` function is never actually called as the array has no elements. See the MDN [Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#Parameters), [Array.prototype.map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) and [Array.prototype.fill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill) for more  info.

Also side note: for something like this, you might want to look into [timesLimit](https://caolan.github.io/async/docs.html#timesLimit). It will call the given function `n` times.

**Comment by ORESoftware** [comment]
yeah you are right, it's weird that `new Array(x)` doesn't work, but that's just one of those JS gotchas, thanks
