### ISSUE TITLE
Strange behavior when using async.waterfall

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1627]
This might be a node.js thing, I am on nodejs version 10.7.0, and async version 2.6.1

I have this code:

```js
const async = require('async');

async.waterfall({
  
  foo(cb){
    cb(null,'b');
  }
  
}, (err,results) => {
   // empty
});

```

when I run it, I get *no output*. But when I run this (I added a console logging statement):

```js
async.waterfall({
  
  foo(cb){
    cb(null,'b');
  }
  
}, (err,results) => {
  console.log({err,results});  // added this line
});
```

I get this:

```
{ err:
   Error: First argument to waterfall must be an array of functions
       at Object.waterfall (/home/oleg/codes/sumanjs/suman-mono/suman/node_modules/async/dist/async.js:5317:42)
       at Object.<anonymous> (/home/oleg/codes/sumanjs/suman-mono/suman/test/async.js:7:7)
       at Module._compile (internal/modules/cjs/loader.js:689:30)
       at startup (internal/bootstrap/node.js:266:19)
       at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3),
  results: undefined }
```

any idea why the discrepancy when the only change is a logging statement? Kinda funny.

**Comment by KarlosQ** [comment]
See docs https://caolan.github.io/async/docs.html#waterfall

First argument must be an array of functions.

The only difference is that in your second example you are logging the error.

**Comment by ORESoftware** [comment]
oh duh, thanks
