### ISSUE TITLE
Undocumented breaking change in v3.2

### ISSUE THREAD

**Issue by binarykitchen** [caolan/async#1710]
Just upgraded from 3.1.1 to latest 3.2.0 and against the changelog it seems to break my app, to come with an undocumented breaking change:

```
[09:41:01] Error: StringMap expected string key
    at stringmap.set (/Users/michael-heuberger/code/videomail.io/node_modules/stringmap/stringmap.js:99:19)
    at Scope.add (/Users/michael-heuberger/code/videomail.io/node_modules/ng-annotate/build/es5/scope.js:102:17)
    at /Users/michael-heuberger/code/videomail.io/node_modules/ng-annotate/build/es5/scopetools.js:65:25
    at Array.forEach (<anonymous>)
    at createScopes (/Users/michael-heuberger/code/videomail.io/node_modules/ng-annotate/build/es5/scopetools.js:64:21)
    at visit (/Users/michael-heuberger/code/videomail.io/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:25:19)
    at visit (/Users/michael-heuberger/code/videomail.io/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:46:21)
    at visit (/Users/michael-heuberger/code/videomail.io/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:43:25)
    at visit (/Users/michael-heuberger/code/videomail.io/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:46:21)
    at visit (/Users/michael-heuberger/code/videomail.io/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:43:25)
```

Smells like a breaking change this isn't mentioned in the changelog.

**Comment by aearly** [comment]
There's not enough information here to know what's going on.

**Comment by achillesoo7** [comment]
Hey @binarykitchen 
According to the stack trace, the error is not from the async I guess, please check the stringmap library.

**Comment by binarykitchen** [comment]
I hear you and think the same. The funny thing is that the above error doesn't happen when I stick to async v3.1.1, only on v3.2.0 - will try to find out myself more ...

**Comment by aearly** [comment]
Please re-open once you have more information.
